name: Continuous Integration

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**.md'
  pull_request:
  workflow_dispatch:

env:
  CMAKE_C_COMPILER_LAUNCHER: ccache
  CMAKE_CXX_COMPILER_LAUNCHER: ccache
  CMAKE_BUILD_TYPE: Debug

jobs:
  maybe_skip:
    runs-on: ubuntu-slim
    outputs:
      should_skip: ${{steps.skip_check.outputs.should_skip}}
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
      id: skip_check
      with:
        cancel_others: 'true'

  build:
    name: build (${{matrix.os}}, ${{matrix.robotology.yarp}}, ${{matrix.compiler.cc}})
    runs-on: ${{matrix.os}}
    needs: maybe_skip
    if: ${{needs.maybe_skip.outputs.should_skip != 'true'}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-26.04]
        robotology:
        - { yarp: yarp-3.12, cmake: 3.22.x }
        - { yarp: yarp-4.0, cmake: 3.22.x }
        - { yarp: master, cmake: 3.22.x }
        compiler:
        - { cc: gcc, cxx: g++ }
        - { cc: clang, cxx: clang++ }
        experimental:
        - ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
        exclude:
        - { experimental: false, robotology: { yarp: master } }

    steps:
    - name: Check out gait-experiments
      uses: actions/checkout@v7

    - name: Check out YCM
      uses: actions/checkout@v7
      with:
        repository: robotology/ycm
        path: .deps/ycm

    - name: Check out YARP
      uses: actions/checkout@v7
      with:
        repository: robotology/yarp
        ref: ${{matrix.robotology.yarp}}
        path: .deps/yarp

    - name: Check out kinematics-dynamics
      uses: actions/checkout@v7
      with:
        repository: roboticslab-uc3m/kinematics-dynamics
        path: .deps/kinematics-dynamics

    - name: Install dependencies via apt
      run: sudo apt-get install -qq ccache liborocos-kdl-dev

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: ${{matrix.robotology.cmake}}

    - name: Set up Ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{matrix.os}}-${{matrix.robotology.yarp}}-${{matrix.compiler.cc}}

    - name: Set environment variables
      run: |
        echo "CC=${{matrix.compiler.cc}}" >> $GITHUB_ENV
        echo "CXX=${{matrix.compiler.cxx}}" >> $GITHUB_ENV

    - name: Set environment variables (YARP next)
      if: ${{matrix.robotology.yarp == 'master'}}
      run: |
        echo "CXXFLAGS=-DYARP_NEXT" >> $GITHUB_ENV

    - name: Build YCM
      run: |
        cmake -S .deps/ycm -B .deps/ycm/build
        cmake --build .deps/ycm/build
        sudo cmake --install .deps/ycm/build

    - name: Build YARP
      run: |
        cmake -S .deps/yarp -B .deps/yarp/build -DSKIP_ACE=ON -DYARP_DISABLE_VERSION_SOURCE=ON -DENABLE_yarpmod_fakeMotionControl=ON
        cmake --build .deps/yarp/build
        sudo cmake --install .deps/yarp/build

    - name: Build kinematics-dynamics
      run: |
        cmake -S .deps/kinematics-dynamics -B .deps/kinematics-dynamics/build
        cmake --build .deps/kinematics-dynamics/build
        sudo cmake --install .deps/kinematics-dynamics/build

    - name: Configure gait-experiments
      run: cmake -S . -B ./build

    - name: Compile gait-experiments
      run: cmake --build ./build

    - name: Install gait-experiments
      run: sudo cmake --install ./build && sudo ldconfig

    - name: Uninstall gait-experiments
      run: sudo cmake --build ./build --target uninstall
